apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  # url: https://argocd.example.com
  # dex.config: |
  #   connectors:
  #     - type: oidc
  #       id: google
  #       name: Google
  #       config:
  #         issuer: https://accounts.google.com
  #         clientID: <id>.apps.googleusercontent.com
  #         clientSecret: $argocd-custom-secret:oidc.google.clientSecret

  # Enable health check for Application resources to make sync-wave work properly:
  # https://kubito.dev/posts/enable-argocd-sync-wave-between-apps/
  resource.customizations.health.argoproj.io_Application: |
    hs = {}
    hs.status = "Progressing"
    hs.message = ""
    if obj.status ~= nil then
      if obj.status.health ~= nil then
        hs.status = obj.status.health.status
        if obj.status.health.message ~= nil then
          hs.message = obj.status.health.message
        end
      end
    end
    return hs

  # Avoid colliding with Kubernetes default selector app.kubernetes.io/instance:
  # https://argo-cd.readthedocs.io/en/stable/faq/#why-is-my-app-out-of-sync-even-after-syncing
  application.instanceLabelKey: argocd.argoproj.io/instance

  # Must explicitly enable helm to support helmCharts property in kustomization.yaml
  kustomize.buildOptions: --load-restrictor LoadRestrictionsNone --enable-helm

  # Ignore differences for commonly troublesome webhooks properties
  resource.customizations.ignoreDifferences.admissionregistration.k8s.io_ValidatingWebhookConfiguration:
    |
    jqPathExpressions:
      - ".webhooks[]?.clientConfig.caBundle"
      - ".webhooks[]?.failurePolicy"
  resource.customizations.ignoreDifferences.admissionregistration.k8s.io_MutatingWebhookConfiguration:
    |
    jqPathExpressions:
      - ".webhooks[]?.clientConfig.caBundle"
      - ".webhooks[]?.failurePolicy"

  # Ignores a dynamically applied Kubernetes feature for Loki: https://github.com/grafana/loki/issues/7249
  resource.customizations.ignoreDifferences.apps_StatefulSet: |
    jsonPointers:
      - /spec/persistentVolumeClaimRetentionPolicy