resources:
  - ./namespace.yaml
  - ./clickhouse.yaml
  - ./qryn.yaml
namespace: logging
helmCharts:
  # Promtail captures logs from all Kubernetes pods and pushes them in batches to Qryn
  - name: promtail
    repo: https://grafana.github.io/helm-charts
    version: 6.11.9
    releaseName: promtail # without this pods are named release-name
    namespace: logging
    valuesInline:
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
      config:
        clients:
          - url: http://qryn:3100/loki/api/v1/push

  # Host OS logs
  # - name: vector
  #   repo: https://helm.vector.dev
  #   releaseName: vector
  #   version: 0.20.1
  #   namespace: logging
  #   valuesInline:
  #     role: "Agent"
  #     podHostNetwork: true
  #     dnsPolicy: ClusterFirstWithHostNet
  #     service:
  #       enabled: false
  #     env:
  #       - name: HOST_IP
  #         valueFrom:
  #           fieldRef:
  #             apiVersion: v1
  #             fieldPath: status.hostIP
  #     tolerations:
  #       - effect: NoSchedule
  #         operator: Exists
  #       - effect: NoExecute
  #         operator: Exists
  #     customConfig:
  #       sources:
  #         talos_kernel_logs:
  #           address: 127.0.0.1:6050
  #           type: socket
  #           mode: tcp
  #           max_length: 102400
  #           decoding:
  #             codec: json
  #         talos_service_logs:
  #           address: 127.0.0.1:6051
  #           type: socket
  #           mode: tcp
  #           max_length: 102400
  #           decoding:
  #             codec: json
  #       transforms:
  #         talos_kernel_logs_transformed:
  #           inputs:
  #             - talos_kernel_logs
  #           type: "remap"
  #           source: |
  #             .hostip = "${HOST_IP}"
  #             .hostname = "${VECTOR_SELF_NODE_NAME}"
  #         talos_service_logs_transformed:
  #           inputs:
  #             - talos_service_logs
  #           type: "remap"
  #           source: |
  #             .hostip = "${HOST_IP}"
  #             .hostname = "${VECTOR_SELF_NODE_NAME}"
  #       sinks:
  #         talos_kernel:
  #           type: loki
  #           inputs:
  #             - talos_kernel_logs_transformed
  #           endpoint: http://loki-gateway.logging.svc
  #           encoding:
  #             codec: json
  #           batch:
  #             max_bytes: 1048576
  #           out_of_order_action: accept
  #           labels:
  #             talos_host: |-
  #               {{`{{ hostname }}`}}
  #             talos_facility: |-
  #               {{`{{ facility }}`}}
  #         talos_service:
  #           type: loki
  #           inputs:
  #             - talos_service_logs_transformed
  #           endpoint: http://loki-gateway.logging.svc
  #           encoding:
  #             codec: json
  #           batch:
  #             max_bytes: 400000
  #           out_of_order_action: accept
  #           labels:
  #             talos_host: |-
  #               {{`{{ hostname }}`}}
  #             talos_service: |-
  #               {{`{{ "talos-service" }}`}}
